### ISSUE TITLE
Wlan0mon

### ISSUE THREAD

**Issue by iiFrog** [3xploitGuy/lazyaircrack#3] opened 2021-01-25 00:30 UTC
Whenever the bash script executes, it looks for wlan0mon specifically, but whenever my adapter is put into monitor mode, it stays as wlan0. Meaning that its looking for the wrong thing and ultimately just doesn't execute

Any fix for this?

**Comment by 3xploitGuy** [comment] 2021-02-06 17:38
Hello, @iiFrog, I think you are getting confused.
wlan0 - managed mode &
wlan0mon - monitor mode
The script takes care of everything, you don't have to put adapter in monitor mode by yourself.
Hope it helps, if you face any error do post the output from your terminal as well. Also do use GitHub Discussions (https://github.com/3xploitGuy/lazyaircrack/discussions) if it's not any major issue and want to discuss about working & features.
The issue will be closed in two days.
Thank You.

**Comment by CobraPearl** [comment] 2021-02-20 23:39
,,,[Input] Path to wordlist (Press enter to use default):                      
[Status] Waiting for Handshake Packet...                                    
[Status] Checking for Handshake Packet...                                   
./lazyaircrack.sh: line 78: logs/password: Permission denied                
[!] Can't find Handshake, waiting ...                                       
[Status] Checking for Handshake Packet...                                   
./lazyaircrack.sh: line 78: logs/password: Permission denied                
[!] Can't find Handshake, waiting ...                                       
[Status] Checking for Handshake Packet...                                   
./lazyaircrack.sh: line 78: logs/password: Permission denied                
[!] Can't find Handshake, waiting ...                                       
[Status] Checking for Handshake Packet...                                   
./lazyaircrack.sh: line 78: logs/password: Permission denied                
[!] Can't find Handshake, waiting ...                                       
[Status] Checking for Handshake Packet...                                   
./lazyaircrack.sh: line 78: logs/password: Permission denied                
[!] Can't find Handshake, waiting ...                                       
[Status] Checking for Handshake Packet...                                   
./lazyaircrack.sh: line 78: logs/password: Permission denied                
[!] Can't find Handshake, waiting ...                                       
[Status] Checking for Handshake Packet...                                   
./lazyaircrack.sh: line 78: logs/password: Permission denied                
./lazyaircrack.sh: line 86: kill: (4070) - No such process                  
rm: cannot remove 'handshake-01.cap': No such file or directory ,,,

Help?

**Comment by 3xploitGuy** [comment] 2021-02-21 17:52
Hello, @CobraPearl the issue is you don't have write access to write the logs in directory, try using script as root. The problem is not related to the LazyAircrack.

**Closed by 3xploitGuy** 2021-02-21 17:52 UTC
